// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class postprofile1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postprofile1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412041725529_postprofile1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
